/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppBotRouteImport } from './routes/_authed/_app/bot'
import { Route as AuthedAppORouteImport } from './routes/_authed/_app/o'
import { Route as AuthedAppPlatformRouteImport } from './routes/_authed/_app/platform'
import { Route as AuthedAppSkillsRouteImport } from './routes/_authed/_app/skills'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminBoundariesRouteImport } from './routes/_authed/admin/boundaries'
import { Route as AuthedAdminComputersRouteImport } from './routes/_authed/admin/computers'
import { Route as AuthedAdminConnectorsRouteImport } from './routes/_authed/admin/connectors'
import { Route as AuthedAdminCredentialsRouteImport } from './routes/_authed/admin/credentials'
import { Route as AuthedAdminIdentityProvidersRouteImport } from './routes/_authed/admin/identity-providers'
import { Route as AuthedAdminPeopleRouteImport } from './routes/_authed/admin/people'
import { Route as AuthedAdminPlaygroundRouteImport } from './routes/_authed/admin/playground'
import { Route as AuthedAdminPluginsRouteImport } from './routes/_authed/admin/plugins'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedAppAgentsIndexRouteImport } from './routes/_authed/_app/agents/index'
import { Route as AuthedAppChannelChannelIdRouteImport } from './routes/_authed/_app/channel/$channelId'
import { Route as AuthedAppChannelNewRouteImport } from './routes/_authed/_app/channel/new'
import { Route as AuthedAppInviteTokenRouteImport } from './routes/_authed/_app/invite.$token'
import { Route as AuthedAppOOrgSlugRouteImport } from './routes/_authed/_app/o.$orgSlug'
import { Route as AuthedAdminComponentsIndexRouteImport } from './routes/_authed/admin/components/index'
import { Route as AuthedAdminComponentsNameRouteImport } from './routes/_authed/admin/components/$name'
import { Route as AuthedAdminConnectorsGoogleDriveRouteImport } from './routes/_authed/admin/connectors/google-drive'
import { Route as AuthedSettingsComponentsGalleryIndexRouteImport } from './routes/_authed/settings/components-gallery/index'
import { Route as AuthedSettingsComponentsGalleryNameRouteImport } from './routes/_authed/settings/components-gallery/$name'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotRoute = AuthedAppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppORoute = AuthedAppORouteImport.update({
  id: '/o',
  path: '/o',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppPlatformRoute = AuthedAppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSkillsRoute = AuthedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminBoundariesRoute = AuthedAdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComputersRoute = AuthedAdminComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminConnectorsRoute = AuthedAdminConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCredentialsRoute = AuthedAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminIdentityProvidersRoute =
  AuthedAdminIdentityProvidersRouteImport.update({
    id: '/identity-providers',
    path: '/identity-providers',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminPeopleRoute = AuthedAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPlaygroundRoute = AuthedAdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsRoute = AuthedAdminPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedAppAgentsIndexRoute = AuthedAppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppChannelChannelIdRoute =
  AuthedAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelNewRoute = AuthedAppChannelNewRouteImport.update({
  id: '/channel/new',
  path: '/channel/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppInviteTokenRoute = AuthedAppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOOrgSlugRoute = AuthedAppOOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthedAppORoute,
} as any)
const AuthedAdminComponentsIndexRoute =
  AuthedAdminComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminComponentsNameRoute =
  AuthedAdminComponentsNameRouteImport.update({
    id: '/components/$name',
    path: '/components/$name',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminConnectorsGoogleDriveRoute =
  AuthedAdminConnectorsGoogleDriveRouteImport.update({
    id: '/google-drive',
    path: '/google-drive',
    getParentRoute: () => AuthedAdminConnectorsRoute,
  } as any)
const AuthedSettingsComponentsGalleryIndexRoute =
  AuthedSettingsComponentsGalleryIndexRouteImport.update({
    id: '/components-gallery/',
    path: '/components-gallery/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsComponentsGalleryNameRoute =
  AuthedSettingsComponentsGalleryNameRouteImport.update({
    id: '/components-gallery/$name',
    path: '/components-gallery/$name',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/bot': typeof AuthedAppBotRoute
  '/o': typeof AuthedAppORouteWithChildren
  '/platform': typeof AuthedAppPlatformRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/connectors': typeof AuthedAdminConnectorsRouteWithChildren
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/plugins': typeof AuthedAdminPluginsRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/invite/$token': typeof AuthedAppInviteTokenRoute
  '/o/$orgSlug': typeof AuthedAppOOrgSlugRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/connectors/google-drive': typeof AuthedAdminConnectorsGoogleDriveRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/agents/': typeof AuthedAppAgentsIndexRoute
  '/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/bot': typeof AuthedAppBotRoute
  '/o': typeof AuthedAppORouteWithChildren
  '/platform': typeof AuthedAppPlatformRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/connectors': typeof AuthedAdminConnectorsRouteWithChildren
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/plugins': typeof AuthedAdminPluginsRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/invite/$token': typeof AuthedAppInviteTokenRoute
  '/o/$orgSlug': typeof AuthedAppOOrgSlugRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/connectors/google-drive': typeof AuthedAdminConnectorsGoogleDriveRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/agents': typeof AuthedAppAgentsIndexRoute
  '/admin/components': typeof AuthedAdminComponentsIndexRoute
  '/settings/components-gallery': typeof AuthedSettingsComponentsGalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/_app/bot': typeof AuthedAppBotRoute
  '/_authed/_app/o': typeof AuthedAppORouteWithChildren
  '/_authed/_app/platform': typeof AuthedAppPlatformRoute
  '/_authed/_app/skills': typeof AuthedAppSkillsRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/_authed/admin/computers': typeof AuthedAdminComputersRoute
  '/_authed/admin/connectors': typeof AuthedAdminConnectorsRouteWithChildren
  '/_authed/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/_authed/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/_authed/admin/people': typeof AuthedAdminPeopleRoute
  '/_authed/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/_authed/admin/plugins': typeof AuthedAdminPluginsRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/_app/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/_authed/_app/channel/new': typeof AuthedAppChannelNewRoute
  '/_authed/_app/invite/$token': typeof AuthedAppInviteTokenRoute
  '/_authed/_app/o/$orgSlug': typeof AuthedAppOOrgSlugRoute
  '/_authed/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/_authed/admin/connectors/google-drive': typeof AuthedAdminConnectorsGoogleDriveRoute
  '/_authed/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/_authed/_app/agents/': typeof AuthedAppAgentsIndexRoute
  '/_authed/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/_authed/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/admin'
    | '/settings'
    | '/bot'
    | '/o'
    | '/platform'
    | '/skills'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/connectors'
    | '/admin/credentials'
    | '/admin/identity-providers'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/plugins'
    | '/admin/'
    | '/settings/'
    | '/channel/$channelId'
    | '/channel/new'
    | '/invite/$token'
    | '/o/$orgSlug'
    | '/admin/components/$name'
    | '/admin/connectors/google-drive'
    | '/settings/components-gallery/$name'
    | '/agents/'
    | '/admin/components/'
    | '/settings/components-gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign'
    | '/bot'
    | '/o'
    | '/platform'
    | '/skills'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/connectors'
    | '/admin/credentials'
    | '/admin/identity-providers'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/plugins'
    | '/admin'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/new'
    | '/invite/$token'
    | '/o/$orgSlug'
    | '/admin/components/$name'
    | '/admin/connectors/google-drive'
    | '/settings/components-gallery/$name'
    | '/agents'
    | '/admin/components'
    | '/settings/components-gallery'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/_authed/admin'
    | '/_authed/settings'
    | '/_authed/_app'
    | '/_authed/_app/bot'
    | '/_authed/_app/o'
    | '/_authed/_app/platform'
    | '/_authed/_app/skills'
    | '/_authed/admin/audit'
    | '/_authed/admin/boundaries'
    | '/_authed/admin/computers'
    | '/_authed/admin/connectors'
    | '/_authed/admin/credentials'
    | '/_authed/admin/identity-providers'
    | '/_authed/admin/people'
    | '/_authed/admin/playground'
    | '/_authed/admin/plugins'
    | '/_authed/_app/'
    | '/_authed/admin/'
    | '/_authed/settings/'
    | '/_authed/_app/channel/$channelId'
    | '/_authed/_app/channel/new'
    | '/_authed/_app/invite/$token'
    | '/_authed/_app/o/$orgSlug'
    | '/_authed/admin/components/$name'
    | '/_authed/admin/connectors/google-drive'
    | '/_authed/settings/components-gallery/$name'
    | '/_authed/_app/agents/'
    | '/_authed/admin/components/'
    | '/_authed/settings/components-gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bot': {
      id: '/_authed/_app/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthedAppBotRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/o': {
      id: '/_authed/_app/o'
      path: '/o'
      fullPath: '/o'
      preLoaderRoute: typeof AuthedAppORouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/platform': {
      id: '/_authed/_app/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthedAppPlatformRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/skills': {
      id: '/_authed/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthedAppSkillsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/boundaries': {
      id: '/_authed/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AuthedAdminBoundariesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/computers': {
      id: '/_authed/admin/computers'
      path: '/computers'
      fullPath: '/admin/computers'
      preLoaderRoute: typeof AuthedAdminComputersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/connectors': {
      id: '/_authed/admin/connectors'
      path: '/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AuthedAdminConnectorsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/credentials': {
      id: '/_authed/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthedAdminCredentialsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/identity-providers': {
      id: '/_authed/admin/identity-providers'
      path: '/identity-providers'
      fullPath: '/admin/identity-providers'
      preLoaderRoute: typeof AuthedAdminIdentityProvidersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/people': {
      id: '/_authed/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthedAdminPeopleRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/playground': {
      id: '/_authed/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AuthedAdminPlaygroundRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins': {
      id: '/_authed/admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthedAdminPluginsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_app/agents/': {
      id: '/_authed/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAppAgentsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/$channelId': {
      id: '/_authed/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthedAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/new': {
      id: '/_authed/_app/channel/new'
      path: '/channel/new'
      fullPath: '/channel/new'
      preLoaderRoute: typeof AuthedAppChannelNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/invite/$token': {
      id: '/_authed/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthedAppInviteTokenRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/o/$orgSlug': {
      id: '/_authed/_app/o/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof AuthedAppOOrgSlugRouteImport
      parentRoute: typeof AuthedAppORoute
    }
    '/_authed/admin/components/': {
      id: '/_authed/admin/components/'
      path: '/components'
      fullPath: '/admin/components/'
      preLoaderRoute: typeof AuthedAdminComponentsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/components/$name': {
      id: '/_authed/admin/components/$name'
      path: '/components/$name'
      fullPath: '/admin/components/$name'
      preLoaderRoute: typeof AuthedAdminComponentsNameRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/connectors/google-drive': {
      id: '/_authed/admin/connectors/google-drive'
      path: '/google-drive'
      fullPath: '/admin/connectors/google-drive'
      preLoaderRoute: typeof AuthedAdminConnectorsGoogleDriveRouteImport
      parentRoute: typeof AuthedAdminConnectorsRoute
    }
    '/_authed/settings/components-gallery/': {
      id: '/_authed/settings/components-gallery/'
      path: '/components-gallery'
      fullPath: '/settings/components-gallery/'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/components-gallery/$name': {
      id: '/_authed/settings/components-gallery/$name'
      path: '/components-gallery/$name'
      fullPath: '/settings/components-gallery/$name'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryNameRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
  }
}

interface AuthedAdminConnectorsRouteChildren {
  AuthedAdminConnectorsGoogleDriveRoute: typeof AuthedAdminConnectorsGoogleDriveRoute
}

const AuthedAdminConnectorsRouteChildren: AuthedAdminConnectorsRouteChildren = {
  AuthedAdminConnectorsGoogleDriveRoute: AuthedAdminConnectorsGoogleDriveRoute,
}

const AuthedAdminConnectorsRouteWithChildren =
  AuthedAdminConnectorsRoute._addFileChildren(
    AuthedAdminConnectorsRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminBoundariesRoute: typeof AuthedAdminBoundariesRoute
  AuthedAdminComputersRoute: typeof AuthedAdminComputersRoute
  AuthedAdminConnectorsRoute: typeof AuthedAdminConnectorsRouteWithChildren
  AuthedAdminCredentialsRoute: typeof AuthedAdminCredentialsRoute
  AuthedAdminIdentityProvidersRoute: typeof AuthedAdminIdentityProvidersRoute
  AuthedAdminPeopleRoute: typeof AuthedAdminPeopleRoute
  AuthedAdminPlaygroundRoute: typeof AuthedAdminPlaygroundRoute
  AuthedAdminPluginsRoute: typeof AuthedAdminPluginsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminComponentsNameRoute: typeof AuthedAdminComponentsNameRoute
  AuthedAdminComponentsIndexRoute: typeof AuthedAdminComponentsIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminBoundariesRoute: AuthedAdminBoundariesRoute,
  AuthedAdminComputersRoute: AuthedAdminComputersRoute,
  AuthedAdminConnectorsRoute: AuthedAdminConnectorsRouteWithChildren,
  AuthedAdminCredentialsRoute: AuthedAdminCredentialsRoute,
  AuthedAdminIdentityProvidersRoute: AuthedAdminIdentityProvidersRoute,
  AuthedAdminPeopleRoute: AuthedAdminPeopleRoute,
  AuthedAdminPlaygroundRoute: AuthedAdminPlaygroundRoute,
  AuthedAdminPluginsRoute: AuthedAdminPluginsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminComponentsNameRoute: AuthedAdminComponentsNameRoute,
  AuthedAdminComponentsIndexRoute: AuthedAdminComponentsIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsComponentsGalleryNameRoute: typeof AuthedSettingsComponentsGalleryNameRoute
  AuthedSettingsComponentsGalleryIndexRoute: typeof AuthedSettingsComponentsGalleryIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsComponentsGalleryNameRoute:
    AuthedSettingsComponentsGalleryNameRoute,
  AuthedSettingsComponentsGalleryIndexRoute:
    AuthedSettingsComponentsGalleryIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedAppORouteChildren {
  AuthedAppOOrgSlugRoute: typeof AuthedAppOOrgSlugRoute
}

const AuthedAppORouteChildren: AuthedAppORouteChildren = {
  AuthedAppOOrgSlugRoute: AuthedAppOOrgSlugRoute,
}

const AuthedAppORouteWithChildren = AuthedAppORoute._addFileChildren(
  AuthedAppORouteChildren,
)

interface AuthedAppRouteChildren {
  AuthedAppBotRoute: typeof AuthedAppBotRoute
  AuthedAppORoute: typeof AuthedAppORouteWithChildren
  AuthedAppPlatformRoute: typeof AuthedAppPlatformRoute
  AuthedAppSkillsRoute: typeof AuthedAppSkillsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppChannelChannelIdRoute: typeof AuthedAppChannelChannelIdRoute
  AuthedAppChannelNewRoute: typeof AuthedAppChannelNewRoute
  AuthedAppInviteTokenRoute: typeof AuthedAppInviteTokenRoute
  AuthedAppAgentsIndexRoute: typeof AuthedAppAgentsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBotRoute: AuthedAppBotRoute,
  AuthedAppORoute: AuthedAppORouteWithChildren,
  AuthedAppPlatformRoute: AuthedAppPlatformRoute,
  AuthedAppSkillsRoute: AuthedAppSkillsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppChannelChannelIdRoute: AuthedAppChannelChannelIdRoute,
  AuthedAppChannelNewRoute: AuthedAppChannelNewRoute,
  AuthedAppInviteTokenRoute: AuthedAppInviteTokenRoute,
  AuthedAppAgentsIndexRoute: AuthedAppAgentsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
